"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowUpRight, BookOpenCheck, BriefcaseBusiness, ChartNoAxesCombined, CheckCircle2, CircleAlert, Landmark, RefreshCw, Scale, WalletCards } from "lucide-react";
import AppShell from "@/components/layout/AppShell";
import { getBalanceSheet, getProfitAndLoss, getTrialBalance, type BalanceSheet, type ProfitAndLoss, type TrialBalance } from "@/services/accountingService";

const money = (value: number) => `₦${Number(value || 0).toLocaleString("en-NG", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export default function AccountingPage() {
  const [trialBalance, setTrialBalance] = useState<TrialBalance | null>(null); const [profitAndLoss, setProfitAndLoss] = useState<ProfitAndLoss | null>(null); const [balanceSheet, setBalanceSheet] = useState<BalanceSheet | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { setError(""); try { const [trial, pnl, balance] = await Promise.all([getTrialBalance(), getProfitAndLoss(), getBalanceSheet()]); setTrialBalance(trial); setProfitAndLoss(pnl); setBalanceSheet(balance); } catch (err) { console.error("Accounting dashboard error", err); setError("The accounting service could not be reached. Check that the API is running and your session is active."); } }, []);
  useEffect(() => { load().finally(() => setLoading(false)); }, [load]);
  const refresh = async () => { setRefreshing(true); await load(); setRefreshing(false); };
  return <AppShell title="Accounting" subtitle="Live financial reporting from posted journal transactions." breadcrumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: "Accounting" }]}>
    <section className="overflow-hidden rounded-[20px] border border-slate-200/90 bg-gradient-to-br from-[#172554] to-[#312e81] text-white shadow-[0_12px_32px_rgba(30,41,59,.14)]"><div className="flex flex-col gap-5 p-6 sm:p-8 lg:flex-row lg:items-center lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-xs font-semibold text-indigo-100"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />Live accounting data</div><h2 className="mt-4 text-2xl font-bold tracking-[-.03em]">Finance control centre</h2><p className="mt-2 max-w-xl text-sm leading-6 text-indigo-100">Every balance on this screen comes from the accounting service’s posted journal entries—there is no frontend financial calculation or duplicate ledger.</p></div><button onClick={refresh} disabled={refreshing} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-indigo-700 transition hover:bg-indigo-50 disabled:opacity-60"><RefreshCw size={16} className={refreshing ? "animate-spin" : ""} />{refreshing ? "Refreshing…" : "Refresh data"}</button></div></section>
    {error ? <section className="flex items-start gap-3 rounded-[20px] border border-rose-200 bg-rose-50 p-5 text-rose-800"><CircleAlert className="mt-0.5 shrink-0" size={20} /><div><h2 className="font-semibold">Accounting data unavailable</h2><p className="mt-1 text-sm text-rose-700">{error}</p><button onClick={refresh} className="mt-4 rounded-lg bg-rose-600 px-3 py-2 text-sm font-semibold text-white hover:bg-rose-700">Try again</button></div></section> : <>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Landmark size={20} />} tint="indigo" label="Total assets" value={loading ? "—" : money(balanceSheet?.total_assets || 0)} note="Resources controlled by the business" /><Metric icon={<WalletCards size={20} />} tint="amber" label="Total liabilities" value={loading ? "—" : money(balanceSheet?.total_liabilities || 0)} note="Current obligations" /><Metric icon={<BriefcaseBusiness size={20} />} tint="violet" label="Equity" value={loading ? "—" : money(balanceSheet?.total_equity_with_profit || 0)} note="Equity including current profit" /><Metric icon={<ChartNoAxesCombined size={20} />} tint={profitAndLoss?.is_profitable ? "emerald" : "rose"} label="Net profit / loss" value={loading ? "—" : money(profitAndLoss?.net_profit || 0)} note={profitAndLoss?.is_profitable ? "Current period is profitable" : "Current period result"} /></section>
      <section className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><div className="overflow-hidden rounded-[20px] border border-slate-200/90 bg-white shadow-[0_6px_20px_rgba(15,23,42,.035)]"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="font-semibold text-slate-900">Profit & loss snapshot</h2><p className="mt-1 text-sm text-slate-500">Income and expenses from the reporting service.</p></div><Link href="/accounting/profit-and-loss" className="grid h-9 w-9 place-items-center rounded-lg text-indigo-600 hover:bg-indigo-50"><ArrowUpRight size={18} /></Link></div><div className="grid sm:grid-cols-3"><Amount label="Revenue" value={profitAndLoss?.total_revenue || 0} /><Amount label="Expenses" value={profitAndLoss?.total_expenses || 0} /><Amount label="Net result" value={profitAndLoss?.net_profit || 0} highlight /></div></div><div className="rounded-[20px] border border-slate-200/90 bg-white p-6 shadow-[0_6px_20px_rgba(15,23,42,.035)]"><div className="flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${trialBalance?.balanced ? "bg-emerald-50 text-emerald-600" : "bg-rose-50 text-rose-600"}`}><Scale size={19} /></span><div><h2 className="font-semibold text-slate-900">Trial balance</h2><p className="text-sm text-slate-500">Ledger integrity status</p></div></div><div className="mt-6 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.08em] text-slate-400">{trialBalance?.accounts.length || 0} active accounts</p><p className="mt-2 text-lg font-bold text-slate-900">{trialBalance?.balanced ? "Books are balanced" : "Review required"}</p></div>{trialBalance?.balanced ? <CheckCircle2 className="text-emerald-500" size={28} /> : <CircleAlert className="text-rose-500" size={28} />}</div><Link href="/accounting/trial-balance" className="mt-5 inline-flex text-sm font-semibold text-indigo-600 hover:text-indigo-800">Open trial balance →</Link></div></section>
      <section><div className="mb-4"><h2 className="font-semibold text-slate-900">Financial reports</h2><p className="mt-1 text-sm text-slate-500">Detailed reports supplied directly by the accounting API.</p></div><div className="grid gap-4 md:grid-cols-3"><ReportLink href="/accounting/trial-balance" icon={<Scale size={20} />} title="Trial balance" description="Review debit and credit totals by account." /><ReportLink href="/accounting/profit-and-loss" icon={<ChartNoAxesCombined size={20} />} title="Profit & loss" description="Analyse revenue, expenses, and the period result." /><ReportLink href="/accounting/balance-sheet" icon={<BookOpenCheck size={20} />} title="Balance sheet" description="Review assets, liabilities, equity, and reconciliation." /></div></section>
    </>}
  </AppShell>;
}
function Metric({ icon, tint, label, value, note }: { icon: React.ReactNode; tint: string; label: string; value: string; note: string }) { const color: Record<string, string> = { indigo: "bg-indigo-50 text-indigo-600", amber: "bg-amber-50 text-amber-600", violet: "bg-violet-50 text-violet-600", emerald: "bg-emerald-50 text-emerald-600", rose: "bg-rose-50 text-rose-600" }; return <div className="rounded-[20px] border border-slate-200/90 bg-white p-5 shadow-[0_6px_20px_rgba(15,23,42,.035)]"><div className="flex items-start justify-between"><p className="text-sm font-medium text-slate-500">{label}</p><span className={`grid h-10 w-10 place-items-center rounded-xl ${color[tint]}`}>{icon}</span></div><p className="mt-4 text-xl font-bold tracking-[-.03em] text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-400">{note}</p></div>; }
function Amount({ label, value, highlight = false }: { label: string; value: number; highlight?: boolean }) { return <div className="border-b border-slate-100 p-6 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><p className="text-sm text-slate-500">{label}</p><p className={`mt-2 text-xl font-bold tracking-tight ${highlight ? value >= 0 ? "text-emerald-600" : "text-rose-600" : "text-slate-900"}`}>{money(value)}</p></div>; }
function ReportLink({ href, icon, title, description }: { href: string; icon: React.ReactNode; title: string; description: string }) { return <Link href={href} className="group rounded-[20px] border border-slate-200/90 bg-white p-5 shadow-[0_6px_20px_rgba(15,23,42,.035)] transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-[0_12px_30px_rgba(15,23,42,.08)]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-indigo-600">{icon}</span><h3 className="mt-4 font-semibold text-slate-900">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{description}</p><span className="mt-4 inline-flex text-sm font-semibold text-indigo-600">Open report <ArrowUpRight className="ml-1 transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5" size={15} /></span></Link>; }
