"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, Download, Printer, ReceiptText, WalletCards } from "lucide-react";
import api from "@/services/api";
import { downloadInvoicePDF } from "@/services/invoiceService";
import AppShell from "@/components/layout/AppShell";

interface Invoice { id: number; invoice_number: string; customer_name: string; amount: string; total_paid: string; balance_due: string; invoice_status: string; due_date: string; created_at: string; items: { id: number; product_name: string; quantity: number; retail_price: string; total_price: string }[]; payments: { id: number; amount_paid: string; payment_date: string }[] }
const money = (value: string | number) => `₦${Number(value || 0).toLocaleString("en-NG", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const status: Record<string, string> = { Paid: "bg-emerald-50 text-emerald-700 ring-emerald-600/20", Overdue: "bg-rose-50 text-rose-700 ring-rose-600/20", "Partially Paid": "bg-indigo-50 text-indigo-700 ring-indigo-600/20" };

export default function InvoiceDetailPage() {
  const router = useRouter(); const params = useParams<{ id: string }>(); const [invoice, setInvoice] = useState<Invoice | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!params?.id) return; api.get(`/invoices/${params.id}/detail/`).then((response) => setInvoice(response.data)).catch((error) => console.error("Invoice Detail Error:", error)).finally(() => setLoading(false)); }, [params?.id]);
  if (loading) return <AppShell title="Invoice" subtitle="Loading invoice details…"><div className="grid gap-4"><div className="h-44 animate-pulse rounded-[20px] bg-slate-200/70" /><div className="h-64 animate-pulse rounded-[20px] bg-slate-200/70" /></div></AppShell>;
  if (!invoice) return <AppShell title="Invoice not found" subtitle="The requested invoice is unavailable."><button onClick={() => router.push("/invoices")} className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Return to invoices</button></AppShell>;
  return <AppShell title={invoice.invoice_number} subtitle={`Invoice for ${invoice.customer_name}`} breadcrumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: "Invoices", href: "/invoices" }, { label: invoice.invoice_number }]}>
    <div className="flex flex-wrap justify-end gap-2"><button onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50"><Printer size={16} />Print</button><button onClick={() => router.push(`/payments/add?invoice=${invoice.id}`)} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-[0_8px_18px_rgba(79,70,229,.22)] hover:bg-indigo-700"><WalletCards size={16} />Record payment</button><button onClick={() => downloadInvoicePDF(invoice.id)} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50"><Download size={16} />PDF</button></div>
    <section className="overflow-hidden rounded-[20px] border border-slate-200/90 bg-white shadow-[0_6px_20px_rgba(15,23,42,.035)]"><div className="flex flex-col justify-between gap-5 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:p-7"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><ReceiptText size={20} /></span><div><p className="text-sm text-slate-500">Customer</p><h2 className="font-semibold text-slate-900">{invoice.customer_name}</h2></div></div><span className={`inline-flex w-fit rounded-full px-3 py-1.5 text-sm font-semibold ring-1 ring-inset ${status[invoice.invoice_status] || "bg-amber-50 text-amber-700 ring-amber-600/20"}`}>{invoice.invoice_status}</span></div><div className="grid divide-y divide-slate-100 sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4"><Metric label="Invoice total" value={money(invoice.amount)} /><Metric label="Amount received" value={money(invoice.total_paid)} /><Metric label="Balance due" value={money(invoice.balance_due)} emphasis /><Metric label="Due date" value={invoice.due_date || "—"} /></div></section>
    <TableCard title="Invoice items" columns={["Product", "Quantity", "Unit price", "Total"]}><tbody className="divide-y divide-slate-100">{invoice.items?.map((item) => <tr key={item.id}><td className="px-6 py-4 text-sm font-medium text-slate-800">{item.product_name}</td><td className="px-6 py-4 text-sm text-slate-600">{item.quantity}</td><td className="px-6 py-4 text-sm text-slate-600">{money(item.retail_price)}</td><td className="px-6 py-4 text-sm font-semibold text-slate-800">{money(item.total_price)}</td></tr>)}</tbody></TableCard>
    <TableCard title="Payment history" columns={["Payment date", "Amount received"]}><tbody className="divide-y divide-slate-100">{invoice.payments?.length ? invoice.payments.map((payment) => <tr key={payment.id}><td className="px-6 py-4 text-sm text-slate-600">{payment.payment_date}</td><td className="px-6 py-4 text-sm font-semibold text-emerald-700">{money(payment.amount_paid)}</td></tr>) : <tr><td colSpan={2} className="px-6 py-10 text-center text-sm text-slate-500">No payments have been recorded for this invoice.</td></tr>}</tbody></TableCard>
    <button onClick={() => router.push("/invoices")} className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-indigo-600"><ArrowLeft size={16} />Back to invoices</button>
  </AppShell>;
}
function Metric({ label, value, emphasis = false }: { label: string; value: string; emphasis?: boolean }) { return <div className="p-5 sm:p-6"><p className="text-xs font-semibold uppercase tracking-[.08em] text-slate-400">{label}</p><p className={`mt-2 text-lg font-bold tracking-tight ${emphasis ? "text-indigo-700" : "text-slate-900"}`}>{value}</p></div>; }
function TableCard({ title, columns, children }: { title: string; columns: string[]; children: React.ReactNode }) { return <section className="overflow-hidden rounded-[20px] border border-slate-200/90 bg-white shadow-[0_6px_20px_rgba(15,23,42,.035)]"><h2 className="border-b border-slate-100 px-6 py-5 font-semibold text-slate-900">{title}</h2><div className="overflow-x-auto"><table className="min-w-[600px] w-full"><thead className="bg-slate-50/80"><tr>{columns.map((column) => <th key={column} className="px-6 py-3.5 text-left text-[11px] font-bold uppercase tracking-[.08em] text-slate-500">{column}</th>)}</tr></thead>{children}</table></div></section>; }
