"use client";

import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { Bell, Building2, Check, CreditCard, Globe2, Palette, ShieldCheck, Users } from "lucide-react";
import AppShell from "@/components/layout/AppShell";

type Settings = { companyName: string; email: string; phone: string; address: string; currency: string; timezone: string; invoicePrefix: string; approvals: boolean; lowStock: boolean; paymentAlerts: boolean };
const defaults: Settings = { companyName: "Tochams Distribution Limited", email: "accounts@tochams.com", phone: "+234", address: "Nigeria", currency: "NGN — Nigerian Naira", timezone: "Africa/Lagos (WAT)", invoicePrefix: "INV-", approvals: true, lowStock: true, paymentAlerts: true };
const input = "mt-2 h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-700 transition focus:border-indigo-300 focus:ring-4 focus:ring-indigo-100";

export default function SettingsPage() {
  const [settings, setSettings] = useState<Settings>(defaults);
  const [active, setActive] = useState("Company");
  useEffect(() => { const saved = window.localStorage.getItem("tochams-erp-settings"); if (saved) setSettings({ ...defaults, ...JSON.parse(saved) }); }, []);
  const update = <K extends keyof Settings>(key: K, value: Settings[K]) => setSettings((current) => ({ ...current, [key]: value }));
  const save = () => { window.localStorage.setItem("tochams-erp-settings", JSON.stringify(settings)); toast.success("Settings saved on this device"); };
  const nav = [{ label: "Company", icon: Building2 }, { label: "Finance", icon: CreditCard }, { label: "Notifications", icon: Bell }, { label: "Access", icon: Users }, { label: "Appearance", icon: Palette }];
  return <AppShell title="Settings" subtitle="Control your organization profile, finance defaults, and workspace preferences." breadcrumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: "Settings" }]}>
    <div className="grid gap-6 lg:grid-cols-[220px_minmax(0,1fr)]"><aside className="h-fit rounded-[20px] border border-slate-200/90 bg-white p-3 shadow-[0_6px_20px_rgba(15,23,42,.035)]"><p className="px-3 pb-3 pt-2 text-[11px] font-bold uppercase tracking-[.1em] text-slate-400">Workspace settings</p>{nav.map((item) => { const Icon = item.icon; return <button key={item.label} onClick={() => setActive(item.label)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${active === item.label ? "bg-indigo-50 text-indigo-700" : "text-slate-600 hover:bg-slate-50"}`}><Icon size={18} />{item.label}</button>; })}</aside>
      <div className="space-y-6"><section className="rounded-[20px] border border-slate-200/90 bg-white p-5 shadow-[0_6px_20px_rgba(15,23,42,.035)] sm:p-7"><div className="flex items-start gap-3 border-b border-slate-100 pb-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Building2 size={19} /></span><div><h2 className="font-semibold text-slate-900">Organization profile</h2><p className="mt-0.5 text-sm text-slate-500">Business information shown on documents and reports.</p></div></div><div className="mt-6 grid gap-5 md:grid-cols-2"><Field label="Company name"><input value={settings.companyName} onChange={(event) => update("companyName", event.target.value)} className={input} /></Field><Field label="Business email"><input type="email" value={settings.email} onChange={(event) => update("email", event.target.value)} className={input} /></Field><Field label="Phone number"><input value={settings.phone} onChange={(event) => update("phone", event.target.value)} className={input} /></Field><Field label="Business address"><input value={settings.address} onChange={(event) => update("address", event.target.value)} className={input} /></Field></div></section>
        <section className="rounded-[20px] border border-slate-200/90 bg-white p-5 shadow-[0_6px_20px_rgba(15,23,42,.035)] sm:p-7"><div className="flex items-start gap-3 border-b border-slate-100 pb-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><Globe2 size={19} /></span><div><h2 className="font-semibold text-slate-900">Finance and regional settings</h2><p className="mt-0.5 text-sm text-slate-500">Set the common defaults used throughout the ERP.</p></div></div><div className="mt-6 grid gap-5 md:grid-cols-3"><Field label="Currency"><select value={settings.currency} onChange={(event) => update("currency", event.target.value)} className={input}><option>NGN — Nigerian Naira</option><option>USD — US Dollar</option><option>GBP — Pound Sterling</option></select></Field><Field label="Timezone"><select value={settings.timezone} onChange={(event) => update("timezone", event.target.value)} className={input}><option>Africa/Lagos (WAT)</option><option>UTC</option></select></Field><Field label="Invoice prefix"><input value={settings.invoicePrefix} onChange={(event) => update("invoicePrefix", event.target.value)} className={input} /></Field></div></section>
        <section className="rounded-[20px] border border-slate-200/90 bg-white p-5 shadow-[0_6px_20px_rgba(15,23,42,.035)] sm:p-7"><div className="flex items-start gap-3 border-b border-slate-100 pb-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-600"><Bell size={19} /></span><div><h2 className="font-semibold text-slate-900">Controls and notifications</h2><p className="mt-0.5 text-sm text-slate-500">Choose which operational events need attention.</p></div></div><div className="mt-3 divide-y divide-slate-100"><Toggle label="Require purchase-order approval" description="New purchase orders must be reviewed before approval." checked={settings.approvals} onChange={(value) => update("approvals", value)} /><Toggle label="Low stock alerts" description="Notify relevant team members when stock reaches reorder level." checked={settings.lowStock} onChange={(value) => update("lowStock", value)} /><Toggle label="Payment notifications" description="Notify accounts when a customer payment is recorded." checked={settings.paymentAlerts} onChange={(value) => update("paymentAlerts", value)} /></div></section>
        <div className="flex items-center justify-between rounded-[20px] border border-indigo-100 bg-indigo-50/60 px-5 py-4"><div className="flex items-center gap-3"><ShieldCheck className="text-indigo-600" size={20} /><p className="text-sm text-indigo-950">Changes are saved locally until organization settings are connected to the backend.</p></div><button onClick={save} className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-[0_8px_18px_rgba(79,70,229,.22)] hover:bg-indigo-700"><Check size={16} />Save changes</button></div>
      </div></div>
  </AppShell>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold text-slate-700">{label}{children}</label>; }
function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex cursor-pointer items-center justify-between gap-5 py-4"><span><span className="block text-sm font-semibold text-slate-800">{label}</span><span className="mt-1 block text-sm text-slate-500">{description}</span></span><input className="peer sr-only" type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span className="relative h-6 w-11 shrink-0 rounded-full bg-slate-200 transition peer-checked:bg-indigo-600 after:absolute after:left-1 after:top-1 after:h-4 after:w-4 after:rounded-full after:bg-white after:shadow-sm after:transition peer-checked:after:translate-x-5" /></label>; }
